# Generated by Django 6.0 on 2026-01-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80, unique=True)),
                ('Slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('Type', models.CharField(choices=[('genre', 'Genre'), ('trope', 'Trope'), ('theme', 'Theme'), ('other', 'Other')], default='other', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Language', models.CharField(blank=True, max_length=32)),
                ('Year', models.PositiveIntegerField(blank=True, null=True)),
                ('ISBN', models.CharField(blank=True, db_index=True, max_length=32)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Authors', models.ManyToManyField(blank=True, related_name='Books', to='catalog.author')),
                ('Tags', models.ManyToManyField(blank=True, related_name='Books', to='catalog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.CharField(choices=[('cover', 'Cover'), ('scan', 'Scan')], max_length=16)),
                ('Image', models.ImageField(upload_to='books/%Y/%m/')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='catalog.book')),
            ],
        ),
    ]
