# Generated by Django 6.0 on 2026-01-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Type',
        ),
        migrations.AlterField(
            model_name='tag',
            name='Slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
